/*
 * This source file was generated by the Gradle 'init' task
 */
package org.controller;

import org.Service.UserService;

import java.io.IOException;
import java.util.Scanner;

public class App {

    //  User Service in Package - Service
    public static UserService userService ;


    public static void main(String [] args) throws IOException{
        main();
    }




    //  Alternative Main method.
    public static void main() throws IOException {


        try{
            userService = new UserService() ;

            Scanner scanner = new Scanner(System.in);

            boolean status = true ;

            while (status){
                System.out.println("******************************************************************************");
                System.out.println("****************************** INOX Movie Ticket Booking *********************");
                System.out.println("******************************************************************************");

                System.out.println("1 - Create new Account");
                System.out.println("2 - Login User");
                System.out.println("3 - Logout User");
                System.out.println("4 - Book Ticket");
                System.out.println("5 - Get Booked Ticket Details");
                System.out.println("6- Exit");

                System.out.println("Please select the options available above :- ");

                int value = scanner.nextInt();

                switch (value){
                    case 1 :
                        //  Create new Account
                        System.out.println("******************************************************************************");
                        System.out.println("******************* Create New User Account **********************************");
                        System.out.println("----- Create new Account -------");
                        System.out.println("Name - ");
                        String tname = scanner.next();
                        System.out.println("Email - ");
                        String temail = scanner.next();
                        System.out.println("Password - ");
                        String tpassword = scanner.next();
                        userService.createUserAccount(temail, tpassword, tname);
                        break;
                    case 2 :
                        //  Login
                        System.out.println("******************************************************************************");
                        System.out.println("******************************** Login User **********************************");
                        System.out.println("---- Login User -------");
                        System.out.println("email - ");
                        String uemail = scanner.next();
                        System.out.println("password - ");
                        String upassword = scanner.next();
                        userService.loginUser(uemail, upassword) ;
                        break;
                    case 3 :
                        //  Logout
                        System.out.println("******************************************************************************");
                        System.out.println("******************************** Logout **************************************");
                        userService.logoutUser();
                        break;
                    case 4 :
                        //  Book Ticket
                        System.out.println("******************************************************************************");
                        System.out.println("******************************* Book Ticket **********************************");
                        userService.bookMovieTicket();
                        break;
                    case 5 :
                        System.out.println("******************************************************************************");
                        System.out.println("******************************** Ticket Details ******************************");
                        userService.bookedTicketDetails();
                        break;
                    case 6 :
                        //  Exit
                        status = false ;
                        System.out.println("Exiting");
                        break;
                    default : System.out.println("Invalid input");
                }
            }


        }
        catch(Exception e){
            System.out.println(e.getMessage());
            e.getStackTrace();
        }

    }
}
